# NixOS starter config for the X470 desktop "pinky" (dev box + Sway)
# Install with the graphical installer first, then copy this file, flake.nix and
# home.nix into /etc/nixos/ and run: sudo nixos-rebuild switch --flake /etc/nixos#pinky
# (see README.md in this folder)

{ config, pkgs, ... }:

{
  imports = [ ./hardware-configuration.nix ]; # generated by the installer, leave it alone

  # --- Boot: systemd-boot on this disk's own EFI partition ---
  boot.loader.systemd-boot.enable = true;
  boot.loader.systemd-boot.configurationLimit = 5; # keep the EFI partition from filling with old generations
  boot.loader.efi.canTouchEfiVariables = true;     # registers NixOS in the firmware boot menu (and makes it the default)

  # --- Graphics: open-source nouveau + NVK (Mesa) for the RTX 2070 ---
  hardware.graphics.enable = true;
  hardware.enableRedistributableFirmware = true;
  boot.kernelParams = [ "nouveau.config=NvGspRm=1" ]; # use NVIDIA's GSP firmware so the GPU can clock up properly on Turing

  # --- Networking ---
  networking.hostName = "pinky";
  networking.networkmanager.enable = true; # Wi-Fi: run `nmtui` for a simple menu

  # --- Locale / time (hardware clock is UTC; Windows was set to match) ---
  time.timeZone = "America/Los_Angeles";
  i18n.defaultLocale = "en_US.UTF-8";

  # --- User (password was set by the installer and is kept) ---
  programs.zsh.enable = true; # needed system-wide for zsh to be a login shell
  users.users.quinn = {
    isNormalUser = true;
    shell = pkgs.zsh;
    extraGroups = [ "wheel" "networkmanager" "video" ];
    # SSH public keys go here once you have them, e.g.:
    # openssh.authorizedKeys.keys = [ "ssh-ed25519 AAAA... you@laptop" ];
  };

  # --- Desktop: niri (scrollable-tiling Wayland) ---
  # The module also sets up the gnome portal (screen sharing) and gnome-keyring.
  programs.niri.enable = true;
  # Login screen on tty1 (greetd + tuigreet) that starts niri. SSH logins don't go through it.
  services.greetd = {
    enable = true;
    useTextGreeter = true; # keep boot messages from scribbling over the TUI
    settings.default_session.command =
      "${pkgs.tuigreet}/bin/tuigreet --time --remember --cmd niri-session";
  };
  security.pam.services.swaylock = { }; # without this swaylock can lock but never unlock

  # --- Audio ---
  security.rtkit.enable = true;
  services.pipewire = {
    enable = true;
    alsa.enable = true;
    pulse.enable = true;
  };

  # --- Remote access (keys only; add your key above first) ---
  services.openssh = {
    enable = true;
    settings.PasswordAuthentication = false;
    settings.PermitRootLogin = "no";
  };
  services.tailscale.enable = true; # run `sudo tailscale up` once to log in

  # --- Run downloaded binaries (Claude Code, mise tools) ---
  # If one fails with "not found": `ldd ./thing | grep "not found"`,
  # then `nix-locate --top-level libfoo.so.1` and add that package here.
  programs.nix-ld = {
    enable = true;
    libraries = with pkgs; [ stdenv.cc.cc.lib zlib openssl curl libffi ];
  };
  programs.command-not-found.enable = false; # doesn't work with flakes; nix-index (home.nix) replaces it

  # --- Software ---
  nixpkgs.config.allowUnfree = true; # 1Password, Spotify, Claude Code are all closed-source
  programs.firefox.enable = true;

  # 1Password: use these modules, not a plain package, so system auth (polkit)
  # and the CLI <-> app integration work
  programs._1password.enable = true; # `op` CLI
  programs._1password-gui = {
    enable = true;
    polkitPolicyOwners = [ "quinn" ]; # lets the app unlock with your system password
  };
  # 1Password is the SSH agent (see home.nix); turn off the one gnome-keyring brings with niri
  services.gnome.gcr-ssh-agent.enable = false;
  environment.systemPackages = with pkgs; [
    git
    ripgrep
    fd

    # what niri/config.kdl launches
    ghostty            # Mod+T  terminal
    fuzzel             # Mod+D  app launcher
    swaylock           # Super+Alt+L  lock screen
    waybar             # status bar, spawned at startup
    xwayland-satellite # niri runs X11 apps through this when it's on PATH
    playerctl          # media keys
  ];
  fonts.packages = with pkgs; [ noto-fonts noto-fonts-color-emoji ];

  # --- Nix itself ---
  nix.settings.experimental-features = [ "nix-command" "flakes" ];

  system.stateVersion = "26.05"; # the release you installed from; don't change this later
}
