# NixOS starter config for the X470 desktop "pinky" (dev box + Sway)
# Install with the graphical installer first, then copy this file, flake.nix and
# home.nix into /etc/nixos/ and run: sudo nixos-rebuild switch --flake /etc/nixos#pinky
# (see README.md in this folder)

{ config, pkgs, ... }:

{
  imports = [ ./hardware-configuration.nix ]; # generated by the installer, leave it alone

  # --- Boot: systemd-boot on this disk's own EFI partition ---
  boot.loader.systemd-boot.enable = true;
  boot.loader.systemd-boot.configurationLimit = 5; # keep the EFI partition from filling with old generations
  boot.loader.efi.canTouchEfiVariables = true;     # registers NixOS in the firmware boot menu (and makes it the default)

  # --- Graphics: open-source nouveau + NVK (Mesa) for the RTX 2070 ---
  hardware.graphics.enable = true;
  hardware.enableRedistributableFirmware = true;
  boot.kernelParams = [ "nouveau.config=NvGspRm=1" ]; # use NVIDIA's GSP firmware so the GPU can clock up properly on Turing

  # --- Networking ---
  networking.hostName = "pinky";
  networking.networkmanager.enable = true; # Wi-Fi: run `nmtui` for a simple menu

  # --- Locale / time (hardware clock is UTC; Windows was set to match) ---
  time.timeZone = "America/Los_Angeles";
  i18n.defaultLocale = "en_US.UTF-8";

  # --- User (password was set by the installer and is kept) ---
  programs.zsh.enable = true; # needed system-wide for zsh to be a login shell
  users.users.quinn = {
    isNormalUser = true;
    shell = pkgs.zsh;
    extraGroups = [ "wheel" "networkmanager" "video" ];
    # SSH public keys go here once you have them, e.g.:
    # openssh.authorizedKeys.keys = [ "ssh-ed25519 AAAA... you@laptop" ];
  };

  # --- Desktop: Sway (Wayland) ---
  programs.sway = {
    enable = true;
    wrapperFeatures.gtk = true;
  };
  # Log in on the text screen (tty1) and Sway starts automatically
  environment.loginShellInit = ''
    if [ "$(tty)" = "/dev/tty1" ]; then exec sway; fi
  '';
  xdg.portal.wlr.enable = true; # screen sharing in browsers etc.

  # --- Audio ---
  security.rtkit.enable = true;
  services.pipewire = {
    enable = true;
    alsa.enable = true;
    pulse.enable = true;
  };

  # --- Remote access (keys only; add your key above first) ---
  services.openssh = {
    enable = true;
    settings.PasswordAuthentication = false;
    settings.PermitRootLogin = "no";
  };
  services.tailscale.enable = true; # run `sudo tailscale up` once to log in

  # --- Run downloaded binaries (Claude Code, mise tools) ---
  # If one fails with "not found": `ldd ./thing | grep "not found"`,
  # then `nix-locate --top-level libfoo.so.1` and add that package here.
  programs.nix-ld = {
    enable = true;
    libraries = with pkgs; [ stdenv.cc.cc.lib zlib openssl curl libffi ];
  };
  programs.command-not-found.enable = false; # doesn't work with flakes; nix-index (home.nix) replaces it

  # --- Software ---
  programs.firefox.enable = true;
  environment.systemPackages = with pkgs; [
    git
    ripgrep
    fd
  ];
  fonts.packages = with pkgs; [ noto-fonts noto-fonts-color-emoji ];

  # --- Nix itself ---
  nix.settings.experimental-features = [ "nix-command" "flakes" ];

  system.stateVersion = "26.05"; # the release you installed from; don't change this later
}
